"use client"

import { Content, Footer, Header } from "antd/es/layout/layout"
import { ConfigProvider, Layout, Spin } from "antd";
import Image from "next/image"
import "@/app/globals.css";
import Link from "next/link";
import { useEffect, useState } from "react";

export const metadata = {
    title: "Cefis Code Review",
    description: "Generated by create next app",
};

export default function ClientLayout({ children }) {
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        const timeout = setTimeout(() => setIsLoading(false), 500)
        return () => clearTimeout(timeout)
    }, []);

    return (
        <html lang="pt-br">
            <body>
                <ConfigProvider>
                    {isLoading ? (
                        <Content
                            style={{
                                padding: '20px 48px 0 48px',
                                minHeight: 'calc(100vh - 131px)',
                                display: 'flex',
                                justifyContent: 'center',
                                alignItems: 'center',
                            }}
                        >
                            <Spin size="large" />
                        </Content>
                    ) : (
                        <Layout style={{ backgroundColor: '#e7e7e7' }}>
                            <Header
                                style={{
                                    position: 'sticky',
                                    top: 0,
                                    zIndex: 1,
                                    width: '100%',
                                    display: 'flex',
                                    alignItems: 'center',
                                }}
                            >
                                <Link href="https://cefis.com.br/" target="_blank" style={{ display: 'flex' }}>
                                    <Image
                                        src='https://cefis.com.br/assets/images/site/svg/logo-cefis-new.svg'
                                        alt='Logo CEFIS'
                                        width='140'
                                        height='40'
                                        priority={true}
                                    />
                                </Link>
                            </Header>
                            <Content
                                style={{
                                    padding: '20px 48px 0 48px',
                                    minHeight: 'calc(100vh - 131px)',
                                }}
                            >
                                { children }
                            </Content>
                            <Footer
                                style={{
                                    textAlign: 'center',
                                }}
                            >
                                CEFIS ©{new Date().getFullYear()}
                            </Footer>
                        </Layout>
                    )}
                </ConfigProvider>
            </body>
        </html>
    )
}